/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, FunctionResult, BamlCtxManager, ClientRegistry, Image, Audio, Pdf, Video, FunctionLog,
HTTPRequest } from "@boundaryml/baml"
import { toBamlError, BamlStream, BamlAbortError, Collector } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {AttendeeProfile, Branding, ConnectionReason, EngagementConfig, EventAppConfig, EventContent, MatchmakingConfig, PartialEventDetails, RelationshipFeatures, SampleAttendee, ScheduleSession, SessionConfig, Speaker, TicketTier, TicketingConfig} from "./types"
import type TypeBuilder from "./type_builder"
import { AsyncHttpRequest, AsyncHttpStreamRequest } from "./async_request"
import { LlmResponseParser, LlmStreamParser } from "./parser"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"
import type * as events from "./events"

/**
* @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
*/
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>

    type TickReason = "Unknown";

    type BamlCallOptions<WatchersT = never> = {
    tb?: TypeBuilder
    clientRegistry?: ClientRegistry
    collector?: Collector | Collector[]
    env?: Record<string, string | undefined>
      tags?: Record<string, string>
        signal?: AbortSignal
        onTick?: (reason: TickReason, log: FunctionLog | null) => void
        watchers?: WatchersT
        }

        export class BamlAsyncClient {
        private runtime: BamlRuntime
        private ctxManager: BamlCtxManager
        private streamClient: BamlStreamClient
        private httpRequest: AsyncHttpRequest
        private httpStreamRequest: AsyncHttpStreamRequest
        private llmResponseParser: LlmResponseParser
        private llmStreamParser: LlmStreamParser
        private bamlOptions: BamlCallOptions

        constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
        this.runtime = runtime
        this.ctxManager = ctxManager
        this.streamClient = new BamlStreamClient(runtime, ctxManager, bamlOptions)
        this.httpRequest = new AsyncHttpRequest(runtime, ctxManager)
        this.httpStreamRequest = new AsyncHttpStreamRequest(runtime, ctxManager)
        this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
        this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
        this.bamlOptions = bamlOptions || {}
        }

        withOptions(bamlOptions: BamlCallOptions) {
        return new BamlAsyncClient(this.runtime, this.ctxManager, bamlOptions)
        }

        get stream() {
        return this.streamClient
        }

        get request() {
        return this.httpRequest
        }

        get streamRequest() {
        return this.httpStreamRequest
        }

        get parse() {
        return this.llmResponseParser
        }

        get parseStream() {
        return this.llmStreamParser
        }

        
        async AnalyzeAttendeeProfile(
        bio: string,whatTheyAreLookingFor: string,whatTheyCanOffer: string,eventGoals: string[],
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.AttendeeProfile> {
          try {
          const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const signal = options.signal;

          if (signal?.aborted) {
          throw new BamlAbortError('Operation was aborted', signal.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (options.onTick) {
          const stream = this.stream.AnalyzeAttendeeProfile(
          bio,whatTheyAreLookingFor,whatTheyCanOffer,eventGoals,
          __baml_options__
          );

          return await stream.getFinalResponse();
          }

          const collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
          [options.collector]) : [];
          const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const env: Record<string, string> = Object.fromEntries(
            Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const raw = await this.runtime.callFunction(
            "AnalyzeAttendeeProfile",
            {
            "bio": bio,"whatTheyAreLookingFor": whatTheyAreLookingFor,"whatTheyCanOffer": whatTheyCanOffer,"eventGoals": eventGoals
            },
            this.ctxManager.cloneContext(),
            options.tb?.__tb(),
            options.clientRegistry,
            collector,
            options.tags || {},
            env,
            signal,
            options.watchers,
            )
            return raw.parsed(false) as types.AttendeeProfile
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async ExtractEventDetails(
        image: Image,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.PartialEventDetails> {
          try {
          const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const signal = options.signal;

          if (signal?.aborted) {
          throw new BamlAbortError('Operation was aborted', signal.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (options.onTick) {
          const stream = this.stream.ExtractEventDetails(
          image,
          __baml_options__
          );

          return await stream.getFinalResponse();
          }

          const collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
          [options.collector]) : [];
          const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const env: Record<string, string> = Object.fromEntries(
            Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const raw = await this.runtime.callFunction(
            "ExtractEventDetails",
            {
            "image": image
            },
            this.ctxManager.cloneContext(),
            options.tb?.__tb(),
            options.clientRegistry,
            collector,
            options.tags || {},
            env,
            signal,
            options.watchers,
            )
            return raw.parsed(false) as types.PartialEventDetails
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async GenerateConnectionReason(
        attendeeA: string,attendeeB: string,sharedTags: string[],sharedIntents: string[],
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.ConnectionReason> {
          try {
          const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const signal = options.signal;

          if (signal?.aborted) {
          throw new BamlAbortError('Operation was aborted', signal.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (options.onTick) {
          const stream = this.stream.GenerateConnectionReason(
          attendeeA,attendeeB,sharedTags,sharedIntents,
          __baml_options__
          );

          return await stream.getFinalResponse();
          }

          const collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
          [options.collector]) : [];
          const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const env: Record<string, string> = Object.fromEntries(
            Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const raw = await this.runtime.callFunction(
            "GenerateConnectionReason",
            {
            "attendeeA": attendeeA,"attendeeB": attendeeB,"sharedTags": sharedTags,"sharedIntents": sharedIntents
            },
            this.ctxManager.cloneContext(),
            options.tb?.__tb(),
            options.clientRegistry,
            collector,
            options.tags || {},
            env,
            signal,
            options.watchers,
            )
            return raw.parsed(false) as types.ConnectionReason
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async GenerateEventAppConfig(
        eventBasics: string,eventDate: string,eventLocation: string,goals: string[],audience: string,relationshipIntent: string,sessionShape: string,matchmakingAppetite: string,tools: string,tone: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.EventAppConfig> {
          try {
          const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const signal = options.signal;

          if (signal?.aborted) {
          throw new BamlAbortError('Operation was aborted', signal.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (options.onTick) {
          const stream = this.stream.GenerateEventAppConfig(
          eventBasics,eventDate,eventLocation,goals,audience,relationshipIntent,sessionShape,matchmakingAppetite,tools,tone,
          __baml_options__
          );

          return await stream.getFinalResponse();
          }

          const collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
          [options.collector]) : [];
          const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const env: Record<string, string> = Object.fromEntries(
            Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
            );
            const raw = await this.runtime.callFunction(
            "GenerateEventAppConfig",
            {
            "eventBasics": eventBasics,"eventDate": eventDate,"eventLocation": eventLocation,"goals": goals,"audience": audience,"relationshipIntent": relationshipIntent,"sessionShape": sessionShape,"matchmakingAppetite": matchmakingAppetite,"tools": tools,"tone": tone
            },
            this.ctxManager.cloneContext(),
            options.tb?.__tb(),
            options.clientRegistry,
            collector,
            options.tags || {},
            env,
            signal,
            options.watchers,
            )
            return raw.parsed(false) as types.EventAppConfig
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
            }

            class BamlStreamClient {
            private runtime: BamlRuntime
            private ctxManager: BamlCtxManager
            private bamlOptions: BamlCallOptions

            constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
            this.runtime = runtime
            this.ctxManager = ctxManager
            this.bamlOptions = bamlOptions || {}
            }

            
            AnalyzeAttendeeProfile(
            bio: string,whatTheyAreLookingFor: string,whatTheyCanOffer: string,eventGoals: string[],
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.AttendeeProfile, types.AttendeeProfile>
              {
              try {
              const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const signal = options.signal;

              if (signal?.aborted) {
              throw new BamlAbortError('Operation was aborted', signal.reason);
              }

              let collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
              [options.collector]) : [];

              let onTickWrapper: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (options.onTick) {
              const tickCollector = new Collector("on-tick-collector");
              collector = [...collector, tickCollector];

              onTickWrapper = () => {
              const log = tickCollector.last;
              if (log) {
              try {
              options.onTick!("Unknown", log);
              } catch (error) {
              console.error("Error in onTick callback for AnalyzeAttendeeProfile", error);
              }
              }
              };
              }

              const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const env: Record<string, string> = Object.fromEntries(
                Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const raw = this.runtime.streamFunction(
                "AnalyzeAttendeeProfile",
                {
                "bio": bio,"whatTheyAreLookingFor": whatTheyAreLookingFor,"whatTheyCanOffer": whatTheyCanOffer,"eventGoals": eventGoals
                },
                undefined,
                this.ctxManager.cloneContext(),
                options.tb?.__tb(),
                options.clientRegistry,
                collector,
                options.tags || {},
                env,
                signal,
                onTickWrapper,
                )
                return new BamlStream<partial_types.AttendeeProfile, types.AttendeeProfile>(
                  raw,
                  (a): partial_types.AttendeeProfile => a,
                  (a): types.AttendeeProfile => a,
                  this.ctxManager.cloneContext(),
                  options.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            ExtractEventDetails(
            image: Image,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.PartialEventDetails, types.PartialEventDetails>
              {
              try {
              const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const signal = options.signal;

              if (signal?.aborted) {
              throw new BamlAbortError('Operation was aborted', signal.reason);
              }

              let collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
              [options.collector]) : [];

              let onTickWrapper: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (options.onTick) {
              const tickCollector = new Collector("on-tick-collector");
              collector = [...collector, tickCollector];

              onTickWrapper = () => {
              const log = tickCollector.last;
              if (log) {
              try {
              options.onTick!("Unknown", log);
              } catch (error) {
              console.error("Error in onTick callback for ExtractEventDetails", error);
              }
              }
              };
              }

              const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const env: Record<string, string> = Object.fromEntries(
                Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const raw = this.runtime.streamFunction(
                "ExtractEventDetails",
                {
                "image": image
                },
                undefined,
                this.ctxManager.cloneContext(),
                options.tb?.__tb(),
                options.clientRegistry,
                collector,
                options.tags || {},
                env,
                signal,
                onTickWrapper,
                )
                return new BamlStream<partial_types.PartialEventDetails, types.PartialEventDetails>(
                  raw,
                  (a): partial_types.PartialEventDetails => a,
                  (a): types.PartialEventDetails => a,
                  this.ctxManager.cloneContext(),
                  options.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            GenerateConnectionReason(
            attendeeA: string,attendeeB: string,sharedTags: string[],sharedIntents: string[],
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.ConnectionReason, types.ConnectionReason>
              {
              try {
              const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const signal = options.signal;

              if (signal?.aborted) {
              throw new BamlAbortError('Operation was aborted', signal.reason);
              }

              let collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
              [options.collector]) : [];

              let onTickWrapper: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (options.onTick) {
              const tickCollector = new Collector("on-tick-collector");
              collector = [...collector, tickCollector];

              onTickWrapper = () => {
              const log = tickCollector.last;
              if (log) {
              try {
              options.onTick!("Unknown", log);
              } catch (error) {
              console.error("Error in onTick callback for GenerateConnectionReason", error);
              }
              }
              };
              }

              const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const env: Record<string, string> = Object.fromEntries(
                Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const raw = this.runtime.streamFunction(
                "GenerateConnectionReason",
                {
                "attendeeA": attendeeA,"attendeeB": attendeeB,"sharedTags": sharedTags,"sharedIntents": sharedIntents
                },
                undefined,
                this.ctxManager.cloneContext(),
                options.tb?.__tb(),
                options.clientRegistry,
                collector,
                options.tags || {},
                env,
                signal,
                onTickWrapper,
                )
                return new BamlStream<partial_types.ConnectionReason, types.ConnectionReason>(
                  raw,
                  (a): partial_types.ConnectionReason => a,
                  (a): types.ConnectionReason => a,
                  this.ctxManager.cloneContext(),
                  options.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            GenerateEventAppConfig(
            eventBasics: string,eventDate: string,eventLocation: string,goals: string[],audience: string,relationshipIntent: string,sessionShape: string,matchmakingAppetite: string,tools: string,tone: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.EventAppConfig, types.EventAppConfig>
              {
              try {
              const options = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const signal = options.signal;

              if (signal?.aborted) {
              throw new BamlAbortError('Operation was aborted', signal.reason);
              }

              let collector = options.collector ? (Array.isArray(options.collector) ? options.collector :
              [options.collector]) : [];

              let onTickWrapper: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (options.onTick) {
              const tickCollector = new Collector("on-tick-collector");
              collector = [...collector, tickCollector];

              onTickWrapper = () => {
              const log = tickCollector.last;
              if (log) {
              try {
              options.onTick!("Unknown", log);
              } catch (error) {
              console.error("Error in onTick callback for GenerateEventAppConfig", error);
              }
              }
              };
              }

              const rawEnv = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const env: Record<string, string> = Object.fromEntries(
                Object.entries(rawEnv).filter(([_, value]) => value !== undefined) as [string, string][]
                );
                const raw = this.runtime.streamFunction(
                "GenerateEventAppConfig",
                {
                "eventBasics": eventBasics,"eventDate": eventDate,"eventLocation": eventLocation,"goals": goals,"audience": audience,"relationshipIntent": relationshipIntent,"sessionShape": sessionShape,"matchmakingAppetite": matchmakingAppetite,"tools": tools,"tone": tone
                },
                undefined,
                this.ctxManager.cloneContext(),
                options.tb?.__tb(),
                options.clientRegistry,
                collector,
                options.tags || {},
                env,
                signal,
                onTickWrapper,
                )
                return new BamlStream<partial_types.EventAppConfig, types.EventAppConfig>(
                  raw,
                  (a): partial_types.EventAppConfig => a,
                  (a): types.EventAppConfig => a,
                  this.ctxManager.cloneContext(),
                  options.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
                  }

                  export const b = new BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
                  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)