/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AttendeeProfile,  Branding,  ConnectionReason,  EngagementConfig,  EventAppConfig,  EventContent,  MatchmakingConfig,  PartialEventDetails,  RelationshipFeatures,  SampleAttendee,  ScheduleSession,  SessionConfig,  Speaker,  TicketTier,  TicketingConfig } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AttendeeProfile {
      tags: string[]
      intents: string[]
      confidenceScores: Record<string, number>
    }
    export interface Branding {
      primaryColor?: string | null
      accentColor?: string | null
      toneKeywords: string[]
    }
    export interface ConnectionReason {
      reasonSummary?: string | null
      talkingPoints: string[]
    }
    export interface EngagementConfig {
      chatEnabled?: boolean | null
      qnaEnabled?: boolean | null
      pollsEnabled?: boolean | null
      liveFeedEnabled?: boolean | null
    }
    export interface EventAppConfig {
      primaryGoals: string[]
      matchmakingConfig?: MatchmakingConfig | null
      sessionConfig?: SessionConfig | null
      engagementConfig?: EngagementConfig | null
      relationshipFeatures?: RelationshipFeatures | null
      branding?: Branding | null
      designNotes?: string | null
      content?: EventContent | null
      ticketing?: TicketingConfig | null
    }
    export interface EventContent {
      eventName?: string | null
      tagline?: string | null
      date?: string | null
      location?: string | null
      speakers: Speaker[]
      schedule: ScheduleSession[]
      sampleAttendees: SampleAttendee[]
    }
    export interface MatchmakingConfig {
      enabled?: boolean | null
      inputSignals: string[]
      matchTypes: string[]
      meetingDurations: number[]
    }
    export interface PartialEventDetails {
      eventName?: string | null
      eventDate?: string | null
      eventLocation?: string | null
      description?: string | null
      vibe?: string | null
    }
    export interface RelationshipFeatures {
      relationshipScoresVisible?: boolean | null
      warmPathHintsEnabled?: boolean | null
      introRequestsEnabled?: boolean | null
    }
    export interface SampleAttendee {
      id?: string | null
      name?: string | null
      imageUrl?: string | null
      interests: string[]
    }
    export interface ScheduleSession {
      id?: string | null
      time?: string | null
      title?: string | null
      speakerName?: string | null
      speakerRole?: string | null
      track?: string | null
      isWide?: boolean | null
    }
    export interface SessionConfig {
      tracksEnabled?: boolean | null
      maxConcurrentSessions?: number | null
      sessionTypes: string[]
    }
    export interface Speaker {
      name?: string | null
      role?: string | null
      company?: string | null
      imageUrl?: string | null
      bio?: string | null
    }
    export interface TicketTier {
      id?: string | null
      name?: string | null
      price?: number | null
      description?: string | null
      features: string[]
    }
    export interface TicketingConfig {
      enabled?: boolean | null
      tiers: TicketTier[]
    }
}