/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AttendeeProfile: ClassViewer<'AttendeeProfile', "tags" | "intents" | "confidenceScores">;
    
    Branding: ClassViewer<'Branding', "primaryColor" | "accentColor" | "toneKeywords">;
    
    ConnectionReason: ClassViewer<'ConnectionReason', "reasonSummary" | "talkingPoints">;
    
    EngagementConfig: ClassViewer<'EngagementConfig', "chatEnabled" | "qnaEnabled" | "pollsEnabled" | "liveFeedEnabled">;
    
    EventAppConfig: ClassViewer<'EventAppConfig', "primaryGoals" | "matchmakingConfig" | "sessionConfig" | "engagementConfig" | "relationshipFeatures" | "branding" | "designNotes">;
    
    MatchmakingConfig: ClassViewer<'MatchmakingConfig', "enabled" | "inputSignals" | "matchTypes" | "meetingDurations">;
    
    RelationshipFeatures: ClassViewer<'RelationshipFeatures', "relationshipScoresVisible" | "warmPathHintsEnabled" | "introRequestsEnabled">;
    
    SessionConfig: ClassViewer<'SessionConfig', "tracksEnabled" | "maxConcurrentSessions" | "sessionTypes">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AttendeeProfile","Branding","ConnectionReason","EngagementConfig","EventAppConfig","MatchmakingConfig","RelationshipFeatures","SessionConfig",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AttendeeProfile = this.tb.classViewer("AttendeeProfile", [
          "tags","intents","confidenceScores",
        ]);
        
        this.Branding = this.tb.classViewer("Branding", [
          "primaryColor","accentColor","toneKeywords",
        ]);
        
        this.ConnectionReason = this.tb.classViewer("ConnectionReason", [
          "reasonSummary","talkingPoints",
        ]);
        
        this.EngagementConfig = this.tb.classViewer("EngagementConfig", [
          "chatEnabled","qnaEnabled","pollsEnabled","liveFeedEnabled",
        ]);
        
        this.EventAppConfig = this.tb.classViewer("EventAppConfig", [
          "primaryGoals","matchmakingConfig","sessionConfig","engagementConfig","relationshipFeatures","branding","designNotes",
        ]);
        
        this.MatchmakingConfig = this.tb.classViewer("MatchmakingConfig", [
          "enabled","inputSignals","matchTypes","meetingDurations",
        ]);
        
        this.RelationshipFeatures = this.tb.classViewer("RelationshipFeatures", [
          "relationshipScoresVisible","warmPathHintsEnabled","introRequestsEnabled",
        ]);
        
        this.SessionConfig = this.tb.classViewer("SessionConfig", [
          "tracksEnabled","maxConcurrentSessions","sessionTypes",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}