/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface AttendeeProfile {
  tags: string[]
  intents: string[]
  confidenceScores: Record<string, number>
  
}

export interface Branding {
  primaryColor: string
  accentColor: string
  toneKeywords: string[]
  
}

export interface ConnectionReason {
  reasonSummary: string
  talkingPoints: string[]
  
}

export interface EngagementConfig {
  chatEnabled: boolean
  qnaEnabled: boolean
  pollsEnabled: boolean
  liveFeedEnabled: boolean
  
}

export interface EventAppConfig {
  primaryGoals: string[]
  matchmakingConfig: MatchmakingConfig
  sessionConfig: SessionConfig
  engagementConfig: EngagementConfig
  relationshipFeatures: RelationshipFeatures
  branding: Branding
  designNotes: string
  content: EventContent
  
}

export interface EventContent {
  eventName: string
  tagline: string
  date: string
  location: string
  speakers: Speaker[]
  schedule: ScheduleSession[]
  sampleAttendees: SampleAttendee[]
  
}

export interface MatchmakingConfig {
  enabled: boolean
  inputSignals: string[]
  matchTypes: string[]
  meetingDurations: number[]
  
}

export interface PartialEventDetails {
  eventName?: string | null
  eventDate?: string | null
  eventLocation?: string | null
  description?: string | null
  vibe?: string | null
  
}

export interface RelationshipFeatures {
  relationshipScoresVisible: boolean
  warmPathHintsEnabled: boolean
  introRequestsEnabled: boolean
  
}

export interface SampleAttendee {
  id: string
  name: string
  imageUrl: string
  interests: string[]
  
}

export interface ScheduleSession {
  id: string
  time: string
  title: string
  speakerName: string
  speakerRole: string
  track: string
  isWide: boolean
  
}

export interface SessionConfig {
  tracksEnabled: boolean
  maxConcurrentSessions: number
  sessionTypes: string[]
  
}

export interface Speaker {
  name: string
  role: string
  company: string
  imageUrl: string
  bio: string
  
}
